### PR TITLE
Manually set DC truncation strategy in AcidicJob::TestCase

### PR DESCRIPTION
**Pull request by julianrubisch**

### CODE REVIEW

**Comment by fractaledmind** [comment]
It is unfortunately much more complicated than this. If the user/system already has a particular DatabaseCleaner configuration, this code will nuke-and-pave that configuration and never restore it. What we have to do instead is mutate whatever the original DatabaseCleaner configuration is in order to transform any transaction strategies into `deletion` strategies. I am cleaning up some code that does this now

**Comment by julianrubisch** [comment]
Ah yeah I actually wanted to do that, but there's no accessor for DC.strategy ...

**Comment by fractaledmind** [comment]
Yeah, it was a bit gnarly, but https://github.com/fractaledmind/acidic_job/pull/19/files should do what we want

**Comment by fractaledmind** [comment]
The short version is that we store whatever the system DatabaseCleaner configuration is at the start of `before_setup` in an instance variable and then restore that configuration at the end of `after_teardown`. In between, we run the configuration thru a pipeline that selectively replaces any `transaction` strategies with a corresponding `deletion` strategy, leaving any other configured strategies untouched.

**Pull request closed without merging**
